version: '3.8'
services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - app_network
networks:
  app_network:
    external: true
